// // Mocks generated by Mockito 5.4.6 from annotations
// // in internappflutter/test/features/AvailableHackathons/domain/usecase/hackathon_usecase_test.dart.
// // Do not manually edit this file.
//
// // ignore_for_file: no_leading_underscores_for_library_prefixes
// import 'dart:async' as _i4;
//
// import 'package:dartz/dartz.dart' as _i2;
// import 'package:internappflutter/features/AvailableHackathons/domain/entities/hackathon_response.dart'
//     as _i6;
// import 'package:internappflutter/features/AvailableHackathons/domain/repository/hackathon_repository.dart'
//     as _i3;
// import 'package:internappflutter/features/core/errors/failiure.dart' as _i5;
// import 'package:mockito/mockito.dart' as _i1;
//
// // ignore_for_file: type=lint
// // ignore_for_file: avoid_redundant_argument_values
// // ignore_for_file: avoid_setters_without_getters
// // ignore_for_file: comment_references
// // ignore_for_file: deprecated_member_use
// // ignore_for_file: deprecated_member_use_from_same_package
// // ignore_for_file: implementation_imports
// // ignore_for_file: invalid_use_of_visible_for_testing_member
// // ignore_for_file: must_be_immutable
// // ignore_for_file: prefer_const_constructors
// // ignore_for_file: unnecessary_parenthesis
// // ignore_for_file: camel_case_types
// // ignore_for_file: subtype_of_sealed_class
// // ignore_for_file: invalid_use_of_internal_member
//
// class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
//   _FakeEither_0(Object parent, Invocation parentInvocation)
//     : super(parent, parentInvocation);
// }
//
// /// A class which mocks [HackathonRepository].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockHackathonRepository extends _i1.Mock
//     implements _i3.HackathonRepository {
//   MockHackathonRepository() {
//     _i1.throwOnMissingStub(this);
//   }
//
//   @override
//   _i4.Future<_i2.Either<_i5.Failure, _i6.HackathonResponse>> getHackathons() =>
//       (super.noSuchMethod(
//             Invocation.method(#getHackathons, []),
//             returnValue:
//                 _i4.Future<
//                   _i2.Either<_i5.Failure, _i6.HackathonResponse>
//                 >.value(
//                   _FakeEither_0<_i5.Failure, _i6.HackathonResponse>(
//                     this,
//                     Invocation.method(#getHackathons, []),
//                   ),
//                 ),
//           )
//           as _i4.Future<_i2.Either<_i5.Failure, _i6.HackathonResponse>>);
//
//   @override
//   _i4.Future<_i2.Either<_i5.Failure, _i6.HackathonResponse>>
//   getSimilarHackathons(String? query) =>
//       (super.noSuchMethod(
//             Invocation.method(#getSimilarHackathons, [query]),
//             returnValue:
//                 _i4.Future<
//                   _i2.Either<_i5.Failure, _i6.HackathonResponse>
//                 >.value(
//                   _FakeEither_0<_i5.Failure, _i6.HackathonResponse>(
//                     this,
//                     Invocation.method(#getSimilarHackathons, [query]),
//                   ),
//                 ),
//           )
//           as _i4.Future<_i2.Either<_i5.Failure, _i6.HackathonResponse>>);
// }
