// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6JRLBGJuZSyh0y3xN9x2i1gqQCO7sV0g',
    appId: '1:730899264601:web:263a8dd28334f7e5876d48',
    messagingSenderId: '730899264601',
    projectId: 'hyrup-84839',
    authDomain: 'hyrup-84839.firebaseapp.com',
    storageBucket: 'hyrup-84839.firebasestorage.app',
    measurementId: 'G-RL3XFHRBV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9u0uPh7VzCGeOOfPecBoyEeXeqBqLs98',
    appId: '1:730899264601:android:2917576ce8e608be876d48',
    messagingSenderId: '730899264601',
    projectId: 'hyrup-84839',
    storageBucket: 'hyrup-84839.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAiTsI2pBivjjBjWd6MaruKwaGPkdXcDY',
    appId: '1:730899264601:ios:23d278cc9f8feafd876d48',
    messagingSenderId: '730899264601',
    projectId: 'hyrup-84839',
    storageBucket: 'hyrup-84839.firebasestorage.app',
    androidClientId: '730899264601-375ndmqrdrqlrjv5jah98gla3hru0ad8.apps.googleusercontent.com',
    iosClientId: '730899264601-kk4a6dd23aoltu8mg6g71d9a7mll24fb.apps.googleusercontent.com',
    iosBundleId: 'com.example.internappflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAiTsI2pBivjjBjWd6MaruKwaGPkdXcDY',
    appId: '1:730899264601:ios:23d278cc9f8feafd876d48',
    messagingSenderId: '730899264601',
    projectId: 'hyrup-84839',
    storageBucket: 'hyrup-84839.firebasestorage.app',
    androidClientId: '730899264601-375ndmqrdrqlrjv5jah98gla3hru0ad8.apps.googleusercontent.com',
    iosClientId: '730899264601-kk4a6dd23aoltu8mg6g71d9a7mll24fb.apps.googleusercontent.com',
    iosBundleId: 'com.example.internappflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6JRLBGJuZSyh0y3xN9x2i1gqQCO7sV0g',
    appId: '1:730899264601:web:fb281db62928109c876d48',
    messagingSenderId: '730899264601',
    projectId: 'hyrup-84839',
    authDomain: 'hyrup-84839.firebaseapp.com',
    storageBucket: 'hyrup-84839.firebasestorage.app',
    measurementId: 'G-SY3GQQ1KM7',
  );
}
